In [2]:
import numpy as np
import pandas as pd

In [3]:
a = np.arange(5)

In [4]:
a

array([0, 1, 2, 3, 4])

In [5]:
a.dtype

dtype('int32')

In [9]:
a.shape

(5,)

In [6]:
m = np.array([np.arange(2), np.arange(2)])

In [7]:
m

array([[0, 1],
       [0, 1]])

In [8]:
m.shape

(2, 2)

In [13]:
a = np.array([[1,2],[3,4]])

In [14]:
a

array([[1, 2],
       [3, 4]])

In [15]:
a[0,0]

1

In [16]:
a[0,1]

2

In [17]:
a[1,0]

3

In [18]:
a[1,1]

4