In [2]:
import numpy as np
import pandas as pd

In [3]:
a = np.arange(5)

In [4]:
a

array([0, 1, 2, 3, 4])

In [5]:
a.dtype

dtype('int64')

In [6]:
a.shape

(5,)

In [7]:
m = np.array([np.arange(2), np.arange(2)])

In [8]:
m

array([[0, 1],
       [0, 1]])

In [9]:
m.shape

(2, 2)

In [10]:
a = np.array([[1,2],[3,4]])

In [11]:
a

array([[1, 2],
       [3, 4]])

In [12]:
a[0,0]

1

In [13]:
a[0,1]

2

In [14]:
a[1,0]

3

In [15]:
a[1,1]

4

In [16]:
b = np.arange(24).reshape(2,3,4)

In [17]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [23]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [24]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [25]:
b.shape = (6,4)

In [26]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [27]:
b.transpose()

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [28]:
b.resize(2,12)

In [29]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [19]:
a = np.arange(9)

In [20]:
a[3:7]

array([3, 4, 5, 6])

In [21]:
a[:7:2]

array([0, 2, 4, 6])

In [22]:
a[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0])