In [2]:
import numpy as np
import pandas as pd

In [3]:
a = np.arange(5)

In [4]:
a

array([0, 1, 2, 3, 4])

In [5]:
a.dtype

dtype('int64')

In [6]:
a.shape

(5,)

In [7]:
m = np.array([np.arange(2), np.arange(2)])

In [8]:
m

array([[0, 1],
       [0, 1]])

In [9]:
m.shape

(2, 2)

In [10]:
a = np.array([[1,2],[3,4]])

In [11]:
a

array([[1, 2],
       [3, 4]])

In [12]:
a[0,0]

1

In [13]:
a[0,1]

2

In [14]:
a[1,0]

3

In [15]:
a[1,1]

4

In [16]:
b = np.arange(24).reshape(2,3,4)

In [17]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [23]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [24]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [25]:
b.shape = (6,4)

In [26]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [27]:
b.transpose()

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [28]:
b.resize(2,12)

In [29]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [30]:
c = b.copy()

In [31]:
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [19]:
a = np.arange(9)

In [20]:
a[3:7]

array([3, 4, 5, 6])

In [21]:
a[:7:2]

array([0, 2, 4, 6])

In [22]:
a[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

In [33]:
b.shape = (6,4)

In [34]:
c.shape = (6,4)

In [35]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [40]:
c = b.copy()

In [41]:
c = c**2

In [42]:
c

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225],
       [256, 289, 324, 361],
       [400, 441, 484, 529]])

In [45]:
np.hstack((b,c))

array([[  0,   1,   2,   3,   0,   1,   4,   9],
       [  4,   5,   6,   7,  16,  25,  36,  49],
       [  8,   9,  10,  11,  64,  81, 100, 121],
       [ 12,  13,  14,  15, 144, 169, 196, 225],
       [ 16,  17,  18,  19, 256, 289, 324, 361],
       [ 20,  21,  22,  23, 400, 441, 484, 529]])

In [46]:
np.vstack((b,c))

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15],
       [ 16,  17,  18,  19],
       [ 20,  21,  22,  23],
       [  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225],
       [256, 289, 324, 361],
       [400, 441, 484, 529]])

In [47]:
np.dstack((b,c))

array([[[  0,   0],
        [  1,   1],
        [  2,   4],
        [  3,   9]],

       [[  4,  16],
        [  5,  25],
        [  6,  36],
        [  7,  49]],

       [[  8,  64],
        [  9,  81],
        [ 10, 100],
        [ 11, 121]],

       [[ 12, 144],
        [ 13, 169],
        [ 14, 196],
        [ 15, 225]],

       [[ 16, 256],
        [ 17, 289],
        [ 18, 324],
        [ 19, 361]],

       [[ 20, 400],
        [ 21, 441],
        [ 22, 484],
        [ 23, 529]]])

In [48]:
oned = np.arange(2)

In [76]:
oned

array([0, 1])

In [49]:
twice_oned = oned * 2

In [77]:
twice_oned

array([0, 2])

In [51]:
np.column_stack((oned, twice_oned))

array([[0, 0],
       [1, 2]])

In [54]:
np.hstack((oned, twice_oned))

array([0, 1, 0, 2])

In [56]:
np.vstack((oned, twice_oned))

array([[0, 1],
       [0, 2]])

In [57]:
np.column_stack((oned, twice_oned)) == np.vstack((oned, twice_oned))

array([[ True, False],
       [False,  True]])

In [52]:
np.column_stack((oned, twice_oned)) == np.hstack((oned, twice_oned))

/Users/yohanlee/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


False

In [58]:
np.row_stack((oned, twice_oned))

array([[0, 1],
       [0, 2]])

In [60]:
np.row_stack((oned, twice_oned)) ==  np.vstack((oned, twice_oned))

array([[ True,  True],
       [ True,  True]])

In [65]:
arr = np.column_stack((oned, twice_oned))

In [66]:
arr

array([[0, 0],
       [1, 2]])

In [67]:
np.hsplit(arr,1)

[array([[0, 0],
        [1, 2]])]

In [68]:
np.hsplit(arr,2)

[array([[0],
        [1]]), array([[0],
        [2]])]

In [70]:
np.vsplit(arr,1)

[array([[0, 0],
        [1, 2]])]

In [72]:
np.vsplit(arr,2)

[array([[0, 0]]), array([[1, 2]])]

In [73]:
arr.ndim

2

In [74]:
arr.T

array([[0, 1],
       [0, 2]])

In [75]:
arr.size

4